/*
 * INTEL CONFIDENTIAL
 * Copyright (c) 2018 Intel Corporation. All Rights Reserved.
 *
 * The source code contained or described herein and all documents related to
 * the source code ("Material") are owned by Intel Corporation or its suppliers
 * or licensors. Title to the Material remains with Intel Corporation or its
 * suppliers and licensors. The Material contains trade secrets and proprietary
 * and confidential information of Intel or its suppliers and licensors. The
 * Material is protected by worldwide copyright and trade secret laws and
 * treaty provisions. No part of the Material may be used, copied, reproduced,
 * modified, published, uploaded, posted, transmitted, distributed, or
 * disclosed in any way without Intel's prior express written permission.
 *
 * No license under any patent, copyright, trade secret or other intellectual
 * property right is granted to or conferred upon you by disclosure or delivery
 * of the Materials, either expressly, by implication, inducement, estoppel or
 * otherwise. Any license under such intellectual property rights must be
 * express and approved by Intel in writing.
 */

/**
 * !! Do not include this file directly !!
 *
 * Include cisu_metadata_base.h instead.
 */

/**
 * ! Do not edit this file directly !
 *
 * Generated automatically from cisu_metadata_tags.mako
 */

/**
 * Top level hierarchy definitions for camera metadata. *_INFO sections are for
 * the static metadata that can be retrived without opening the camera device.
 * New sections must be added right before CISU_SECTION_COUNT to maintain
 * existing enumerations.
 */
typedef enum cisuMetadataSection {
    CISU_TUNED_MODES,
    CISU_AE_CONTROL,
    CISU_AE_FEATURES,
    CISU_FLASH_CONTROL__W_I_P_,
    CISU_AF_CONTROL,
    CISU_AWB_CONTROL,
    CISU_STATISTICS,
    CISU_GBCE_CONTROL,
    CISU_SHADING_ADAPTOR,
    CISU_COLOR_CONTROL,
    CISU_ISP_CONTROL,
    CISU_DVS_CONTROL,
    CISU_SIMULATION_CONTROL,
    CISU_SECTION_COUNT
} cisu_metadata_section_t;

/**
 * Hierarchy positions in enum space.
 */
typedef enum cisuMetadataSection_start {
    CISU_TUNED_MODES_START         = CISU_TUNED_MODES          << 16,
    CISU_AE_CONTROL_START          = CISU_AE_CONTROL           << 16,
    CISU_AE_FEATURES_START         = CISU_AE_FEATURES          << 16,
    CISU_FLASH_CONTROL__W_I_P__START
                                   = CISU_FLASH_CONTROL__W_I_P_
                                                                << 16,
    CISU_AF_CONTROL_START          = CISU_AF_CONTROL           << 16,
    CISU_AWB_CONTROL_START         = CISU_AWB_CONTROL          << 16,
    CISU_STATISTICS_START          = CISU_STATISTICS           << 16,
    CISU_GBCE_CONTROL_START        = CISU_GBCE_CONTROL         << 16,
    CISU_SHADING_ADAPTOR_START     = CISU_SHADING_ADAPTOR      << 16,
    CISU_COLOR_CONTROL_START       = CISU_COLOR_CONTROL        << 16,
    CISU_ISP_CONTROL_START         = CISU_ISP_CONTROL          << 16,
    CISU_DVS_CONTROL_START         = CISU_DVS_CONTROL          << 16,
    CISU_SIMULATION_CONTROL_START  = CISU_SIMULATION_CONTROL   << 16,
} cisu_metadata_section_start_t;

/**
 * Main enum for defining camera metadata tags.  New entries must always go
 * before the section _END tag to preserve existing enumeration values.  In
 * addition, the name and type of the tag needs to be added to
 * system/media/camera/src/cisu_metadata_tag_info.c
 */
enum cisuMetadataTag {
    CISU_TUNED_MODES_INSTANT_CONVERGENCE =            // enum         | system
            CISU_TUNED_MODES_START,
    CISU_TUNED_MODES_AIQ_MODE,                        // int32        | public
    CISU_TUNED_MODES_AVAILABLE_AIQ_MODE,              // int32[]      | public
    CISU_TUNED_MODES_CMC_MODE,                        // int32        | public
    CISU_TUNED_MODES_END,

    CISU_AE_CONTROL_OPERATION_MODE =                  // enum         | public
            CISU_AE_CONTROL_START,
    CISU_AE_CONTROL_METERING_MODE,                    // enum         | public
    CISU_AE_CONTROL_PRIORITY_MODE,                    // enum         | public
    CISU_AE_CONTROL_FLICKER_REDUCTION,                // enum         | public
    CISU_AE_CONTROL_EXPOSURE_WINDOW,                  // int32[]      | public
    CISU_AE_CONTROL_EXPOSURE_COORDINATE,              // int32[]      | public
    CISU_AE_CONTROL_EV_SHIFT,                         // float        | public
    CISU_AE_CONTROL_MANUAL_EXPOSURE_LIMITS_US,        // int32[]      | public
    CISU_AE_CONTROL_MANUAL_ANALOG_GAIN,               // float        | public
    CISU_AE_CONTROL_MANUAL_ISO,                       // byte         | public
    CISU_AE_CONTROL_MANUAL_APERTURE_FN,               // float        | public
    CISU_AE_CONTROL_EXPOSURE_DISTRIBUTION_PRIORITY,   // enum         | public
    CISU_AE_CONTROL_MANUAL_FRAME_RATE,                // int32[]      | public
    CISU_AE_CONTROL_CONVERGENCE_TIME,                 // float        | public
    CISU_AE_CONTROL_AVAILABLE_OPERATION_MODE,         // byte[]       | public
    CISU_AE_CONTROL_AVAILABLE_METERING_MODE,          // byte[]       | public
    CISU_AE_CONTROL_AVAILABLE_PRIORITY_MODE,          // byte[]       | public
    CISU_AE_CONTROL_AVAILABLE_FLICKER_REDUCTION,      // byte[]       | public
    CISU_AE_CONTROL_AVAILABLE_EXPOSURE_DISTRIBUTION_PRIORITY,
                                                      // byte[]       | public
    CISU_AE_CONTROL_EXPOSURE_TIME,                    // int32        | public
    CISU_AE_CONTROL_ANALOG_GAIN,                      // float        | public
    CISU_AE_CONTROL_DIGITAL_GAIN,                     // float        | public
    CISU_AE_CONTROL_APERTURE_FN,                      // float        | public
    CISU_AE_CONTROL_ISO,                              // int32        | public
    CISU_AE_CONTROL_TOTAL_TARGET_EXPOSURE,            // int32        | public
    CISU_AE_CONTROL_AE_CONVERGED,                     // enum         | system
    CISU_AE_CONTROL_END,

    CISU_AE_FEATURES_MOTION_BLUR_CONTROL_SETTING =    // enum         | public
            CISU_AE_FEATURES_START,
    CISU_AE_FEATURES_BACKLIGHT_COMPENSATION_SETTING,  // enum         | public
    CISU_AE_FEATURES_FACE_UTILIZATION_SETTING,        // enum         | public
    CISU_AE_FEATURES_RED_EYE_REDUCTION_FLASH_SETTING, // enum         | public
    CISU_AE_FEATURES_FILL_IN_FLASH_SETTING,           // enum         | public
    CISU_AE_FEATURES_CONTINUOUS_FLICKER_DETECTION_SETTING,
                                                      // enum         | public
    CISU_AE_FEATURES_AVAILABLE_MOTION_BLUR_CONTROL_SETTING,
                                                      // byte[]       | public
    CISU_AE_FEATURES_AVAILABLE_BACKLIGHT_COMPENSATION_SETTING,
                                                      // byte[]       | public
    CISU_AE_FEATURES_AVAILABLE_FACE_UTILIZATION_SETTING,
                                                      // byte[]       | public
    CISU_AE_FEATURES_AVAILABLE_RED_EYE_REDUCTION_FLASH_SETTING,
                                                      // byte[]       | public
    CISU_AE_FEATURES_AVAILABLE_FILL_IN_FLASH_SETTING, // byte[]       | public
    CISU_AE_FEATURES_AVAILABLE_CONTINUOUS_FLICKER_DETECTION_SETTING,
                                                      // byte[]       | public
    CISU_AE_FEATURES_END,

    CISU_FLASH_CONTROL__W_I_P__OPERATION_MODE =       // enum         | public
            CISU_FLASH_CONTROL__W_I_P__START,
    CISU_FLASH_CONTROL__W_I_P__AVAILABLE_OPERATION_MODE,
                                                      // byte[]       | public
    CISU_FLASH_CONTROL__W_I_P__FLASH_STATE,           // enum         | public
    CISU_FLASH_CONTROL__W_I_P__END,

    CISU_AF_CONTROL_OPERATION_MODE =                  // enum         | public
            CISU_AF_CONTROL_START,
    CISU_AF_CONTROL_MANUAL_FOCUS_DISTANCE,            // int32        | public
    CISU_AF_CONTROL_MANUAL_FOCAL_DISTANCE,            // int32        | public
    CISU_AF_CONTROL_AVAILABLE_OPERATION_MODE,         // byte[]       | public
    CISU_AF_CONTROL_LENS_POSITION,                    // int32        | public
    CISU_AF_CONTROL_LENS_MOVEMENT_STARTTIMESTAMP,     // int64        | public
    CISU_AF_CONTROL_AF_STATE,                         // enum         | public
    CISU_AF_CONTROL_CURRENT_FOCUS_DISTANCE,           // int32        | system
    CISU_AF_CONTROL_FINAL_LENS_POSITION_REACHED,      // enum         | system
    CISU_AF_CONTROL_END,

    CISU_AWB_CONTROL_OPERATION_MODE =                 // enum         | public
            CISU_AWB_CONTROL_START,
    CISU_AWB_CONTROL_MANUAL_CCT_RANGE,                // int32[]      | public
    CISU_AWB_CONTROL_MANUAL_WHITE_COORDINATE,         // int32[]      | public
    CISU_AWB_CONTROL_AVAILABLE_OPERATION_MODE,        // byte[]       | public
    CISU_AWB_CONTROL_ACCURATE_RED_PER_GREEN,          // float        | system
    CISU_AWB_CONTROL_ACCURATE_BLUE_PER_GREEN,         // float        | system
    CISU_AWB_CONTROL_FINAL_RED_PER_GREEN,             // float        | system
    CISU_AWB_CONTROL_FINAL_BLUE_PER_GREEN,            // float        | system
    CISU_AWB_CONTROL_CCT_ESTIMATE,                    // int32        | system
    CISU_AWB_CONTROL_DISTANCE_FROM_CONVERGENCE,       // float        | system
    CISU_AWB_CONTROL_END,

    CISU_STATISTICS_HISTOGRAM_WEIGHT_GRID_SIZE =      // int32[]      | public
            CISU_STATISTICS_START,
    CISU_STATISTICS_HISTOGRAM_WEIGHT_GRID_MULTIPLIERS,// byte[]       | public
    CISU_STATISTICS_END,

    CISU_GBCE_CONTROL_GAMMA_TYPE =                    // enum         | public
            CISU_GBCE_CONTROL_START,
    CISU_GBCE_CONTROL_AVAILABLE_GAMMA_TYPE,           // int32[]      | public
    CISU_GBCE_CONTROL_TONEMAP_LUT_SIZE,               // int32        | public
    CISU_GBCE_CONTROL_TONEMAP_LUT,                    // float[]      | system
    CISU_GBCE_CONTROL_END,

    CISU_SHADING_ADAPTOR_LSC_GRID =                   // int32[]      | system
            CISU_SHADING_ADAPTOR_START,
    CISU_SHADING_ADAPTOR_LSC_GRID_WITDTH,             // int32        | system
    CISU_SHADING_ADAPTOR_LSC_GRID_HEIGHT,             // int32        | system
    CISU_SHADING_ADAPTOR_FRACTION_BITS,               // int32        | system
    CISU_SHADING_ADAPTOR_END,

    CISU_COLOR_CONTROL_CC_MATRIX =                    // float[]      | system
            CISU_COLOR_CONTROL_START,
    CISU_COLOR_CONTROL_BLACK_LEVEL_CC,                // float[]      | system
    CISU_COLOR_CONTROL_COLOR_GAIN,                    // float[]      | system
    CISU_COLOR_CONTROL_ADVANCED_CCM_SECTOR_COUNT,     // int32        | system
    CISU_COLOR_CONTROL_ADVANCED_CC_MATRICES,          // float[]      | system
    CISU_COLOR_CONTROL_END,

    CISU_ISP_CONTROL_EFFECT_MODE =                    // enum         | public
            CISU_ISP_CONTROL_START,
    CISU_ISP_CONTROL_NR_SETTING_LEVEL,                // enum         | public
    CISU_ISP_CONTROL_NR_SETTING_STRENGTH,             // byte         | public
    CISU_ISP_CONTROL_EE_SETTING_LEVEL,                // enum         | public
    CISU_ISP_CONTROL_EE_SETTING_STRENGTH,             // byte         | public
    CISU_ISP_CONTROL_AVAILABLE_EFFECT_MODE,           // byte[]       | public
    CISU_ISP_CONTROL_AVAILABLE_NR_SETTINGS,           // byte[]       | public
    CISU_ISP_CONTROL_AVAILABLE_EE_SETTINGS,           // byte[]       | public
    CISU_ISP_CONTROL_END,

    CISU_DVS_CONTROL_DVS_OPERATION_MODE =             // enum         | public
            CISU_DVS_CONTROL_START,
    CISU_DVS_CONTROL_AVAILABLE_DVS_OPERATION_MODE,    // byte[]       | public
    CISU_DVS_CONTROL_END,

    CISU_SIMULATION_CONTROL_MODE =                    // enum         | public
            CISU_SIMULATION_CONTROL_START,
    CISU_SIMULATION_CONTROL_FILTER_DUMP_NAMES,        // byte[]       | public
    CISU_SIMULATION_CONTROL_FILTER_DUMP_PATH,         // byte[]       | public
    CISU_SIMULATION_CONTROL_FILTER_DUMP_NAME_LENGTH,  // int32        | public
    CISU_SIMULATION_CONTROL_FILTER_INPUT_FILE_PATH_TYPE,
                                                      // enum         | public
    CISU_SIMULATION_CONTROL_FILTER_INPUT_FILE_NAMES,  // byte[]       | public
    CISU_SIMULATION_CONTROL_FILTER_INPUT_FILE_NAME_LENGTH,
                                                      // int32        | public
    CISU_SIMULATION_CONTROL_AVAILABLE_SIMULATION_MODE,// byte[]       | public
    CISU_SIMULATION_CONTROL_END,

};

/**
 * Enumeration definitions for the various entries that need them
 */

// CISU_TUNED_MODES_INSTANT_CONVERGENCE
enum cisu_metadata_enum_cisu_tuned_modes_instant_convergence {
    CISU_TUNED_MODES_INSTANT_CONVERGENCE_FALSE,
    CISU_TUNED_MODES_INSTANT_CONVERGENCE_TRUE,
};


// CISU_AE_CONTROL_OPERATION_MODE
enum cisu_metadata_enum_cisu_ae_control_operation_mode {
    CISU_AE_CONTROL_OPERATION_MODE_AUTOMATIC,
    CISU_AE_CONTROL_OPERATION_MODE_LONG_EXPOSURE,
    CISU_AE_CONTROL_OPERATION_MODE_ACTION,
    CISU_AE_CONTROL_OPERATION_MODE_VIDEO_CONFERENCE,
    CISU_AE_CONTROL_OPERATION_MODE_PRODUCTION_TEST,
    CISU_AE_CONTROL_OPERATION_MODE_ULTRA_LOW_LIGHT,
    CISU_AE_CONTROL_OPERATION_MODE_FIREWORKS,
    CISU_AE_CONTROL_OPERATION_MODE_HDR,
    CISU_AE_CONTROL_OPERATION_MODE_CUSTOM_1,
    CISU_AE_CONTROL_OPERATION_MODE_CUSTOM_2,
    CISU_AE_CONTROL_OPERATION_MODE_CUSTOM_3,
};

// CISU_AE_CONTROL_METERING_MODE
enum cisu_metadata_enum_cisu_ae_control_metering_mode {
    CISU_AE_CONTROL_METERING_MODE_EVALUATIVE,
    CISU_AE_CONTROL_METERING_MODE_CENTER,
};

// CISU_AE_CONTROL_PRIORITY_MODE
enum cisu_metadata_enum_cisu_ae_control_priority_mode {
    CISU_AE_CONTROL_PRIORITY_MODE_NORMAL,
    CISU_AE_CONTROL_PRIORITY_MODE_HIGHLIGHT,
    CISU_AE_CONTROL_PRIORITY_MODE_SHADOW,
};

// CISU_AE_CONTROL_FLICKER_REDUCTION
enum cisu_metadata_enum_cisu_ae_control_flicker_reduction {
    CISU_AE_CONTROL_FLICKER_REDUCTION_OFF,
    CISU_AE_CONTROL_FLICKER_REDUCTION_50Hz,
    CISU_AE_CONTROL_FLICKER_REDUCTION_60Hz,
    CISU_AE_CONTROL_FLICKER_REDUCTION_AUTO,
    CISU_AE_CONTROL_FLICKER_REDUCTION_DETECT,
};

// CISU_AE_CONTROL_EXPOSURE_DISTRIBUTION_PRIORITY
enum cisu_metadata_enum_cisu_ae_control_exposure_distribution_priority {
    CISU_AE_CONTROL_EXPOSURE_DISTRIBUTION_PRIORITY_AUTO,
    CISU_AE_CONTROL_EXPOSURE_DISTRIBUTION_PRIORITY_SHUTTER,
    CISU_AE_CONTROL_EXPOSURE_DISTRIBUTION_PRIORITY_ISO,
    CISU_AE_CONTROL_EXPOSURE_DISTRIBUTION_PRIORITY_APERTURE,
};

// CISU_AE_CONTROL_AE_CONVERGED
enum cisu_metadata_enum_cisu_ae_control_ae_converged {
    CISU_AE_CONTROL_AE_CONVERGED_FALSE,
    CISU_AE_CONTROL_AE_CONVERGED_TRUE,
};


// CISU_AE_FEATURES_MOTION_BLUR_CONTROL_SETTING
enum cisu_metadata_enum_cisu_ae_features_motion_blur_control_setting {
    CISU_AE_FEATURES_MOTION_BLUR_CONTROL_SETTING_TUNING,
    CISU_AE_FEATURES_MOTION_BLUR_CONTROL_SETTING_DISABLED,
    CISU_AE_FEATURES_MOTION_BLUR_CONTROL_SETTING_ENABLED,
};

// CISU_AE_FEATURES_BACKLIGHT_COMPENSATION_SETTING
enum cisu_metadata_enum_cisu_ae_features_backlight_compensation_setting {
    CISU_AE_FEATURES_BACKLIGHT_COMPENSATION_SETTING_TUNING,
    CISU_AE_FEATURES_BACKLIGHT_COMPENSATION_SETTING_DISABLED,
    CISU_AE_FEATURES_BACKLIGHT_COMPENSATION_SETTING_ENABLED,
};

// CISU_AE_FEATURES_FACE_UTILIZATION_SETTING
enum cisu_metadata_enum_cisu_ae_features_face_utilization_setting {
    CISU_AE_FEATURES_FACE_UTILIZATION_SETTING_TUNING,
    CISU_AE_FEATURES_FACE_UTILIZATION_SETTING_DISABLED,
    CISU_AE_FEATURES_FACE_UTILIZATION_SETTING_ENABLED,
};

// CISU_AE_FEATURES_RED_EYE_REDUCTION_FLASH_SETTING
enum cisu_metadata_enum_cisu_ae_features_red_eye_reduction_flash_setting {
    CISU_AE_FEATURES_RED_EYE_REDUCTION_FLASH_SETTING_TUNING,
    CISU_AE_FEATURES_RED_EYE_REDUCTION_FLASH_SETTING_DISABLED,
    CISU_AE_FEATURES_RED_EYE_REDUCTION_FLASH_SETTING_ENABLED,
};

// CISU_AE_FEATURES_FILL_IN_FLASH_SETTING
enum cisu_metadata_enum_cisu_ae_features_fill_in_flash_setting {
    CISU_AE_FEATURES_FILL_IN_FLASH_SETTING_TUNING,
    CISU_AE_FEATURES_FILL_IN_FLASH_SETTING_DISABLED,
    CISU_AE_FEATURES_FILL_IN_FLASH_SETTING_ENABLED,
};

// CISU_AE_FEATURES_CONTINUOUS_FLICKER_DETECTION_SETTING
enum cisu_metadata_enum_cisu_ae_features_continuous_flicker_detection_setting {
    CISU_AE_FEATURES_CONTINUOUS_FLICKER_DETECTION_SETTING_TUNING,
    CISU_AE_FEATURES_CONTINUOUS_FLICKER_DETECTION_SETTING_DISABLED,
    CISU_AE_FEATURES_CONTINUOUS_FLICKER_DETECTION_SETTING_ENABLED,
};


// CISU_FLASH_CONTROL__W_I_P__OPERATION_MODE
enum cisu_metadata_enum_cisu_flash_control__w_i_p__operation_mode {
    CISU_FLASH_CONTROL__W_I_P__OPERATION_MODE_AUTO,
    CISU_FLASH_CONTROL__W_I_P__OPERATION_MODE_ON,
    CISU_FLASH_CONTROL__W_I_P__OPERATION_MODE_OFF,
};

// CISU_FLASH_CONTROL__W_I_P__FLASH_STATE
enum cisu_metadata_enum_cisu_flash_control__w_i_p__flash_state {
    CISU_FLASH_CONTROL__W_I_P__FLASH_STATE_NO,
    CISU_FLASH_CONTROL__W_I_P__FLASH_STATE_TORCH,
    CISU_FLASH_CONTROL__W_I_P__FLASH_STATE_PRE_FLASH,
    CISU_FLASH_CONTROL__W_I_P__FLASH_STATE_MAIN_FLASH,
    CISU_FLASH_CONTROL__W_I_P__FLASH_STATE_RED_EYE,
};


// CISU_AF_CONTROL_OPERATION_MODE
enum cisu_metadata_enum_cisu_af_control_operation_mode {
    CISU_AF_CONTROL_OPERATION_MODE_AUTO,
    CISU_AF_CONTROL_OPERATION_MODE_INFINITY,
    CISU_AF_CONTROL_OPERATION_MODE_HYPERFOCAL,
    CISU_AF_CONTROL_OPERATION_MODE_MANUAL,
    CISU_AF_CONTROL_OPERATION_MODE_CONSTRAST,
};

// CISU_AF_CONTROL_AF_STATE
enum cisu_metadata_enum_cisu_af_control_af_state {
    CISU_AF_CONTROL_AF_STATE_IDLE,
    CISU_AF_CONTROL_AF_STATE_SEARCH,
    CISU_AF_CONTROL_AF_STATE_SUCCESS,
    CISU_AF_CONTROL_AF_STATE_FAIL,
};

// CISU_AF_CONTROL_FINAL_LENS_POSITION_REACHED
enum cisu_metadata_enum_cisu_af_control_final_lens_position_reached {
    CISU_AF_CONTROL_FINAL_LENS_POSITION_REACHED_FALSE,
    CISU_AF_CONTROL_FINAL_LENS_POSITION_REACHED_TRUE,
};


// CISU_AWB_CONTROL_OPERATION_MODE
enum cisu_metadata_enum_cisu_awb_control_operation_mode {
    CISU_AWB_CONTROL_OPERATION_MODE_AUTO,
    CISU_AWB_CONTROL_OPERATION_MODE_DAYLIGHT,
    CISU_AWB_CONTROL_OPERATION_MODE_PARTLY_OVERCAST,
    CISU_AWB_CONTROL_OPERATION_MODE_FULLY_OVERCAST,
    CISU_AWB_CONTROL_OPERATION_MODE_FLUORESCENT,
    CISU_AWB_CONTROL_OPERATION_MODE_INCANDESCENT,
    CISU_AWB_CONTROL_OPERATION_MODE_SUNSET,
    CISU_AWB_CONTROL_OPERATION_MODE_VIDEO_CONFERENCE,
    CISU_AWB_CONTROL_OPERATION_MODE_CANDLELIGHT,
    CISU_AWB_CONTROL_OPERATION_MODE_FLASH,
    CISU_AWB_CONTROL_OPERATION_MODE_SNOW,
    CISU_AWB_CONTROL_OPERATION_MODE_BEACH,
};



// CISU_GBCE_CONTROL_GAMMA_TYPE
enum cisu_metadata_enum_cisu_gbce_control_gamma_type {
    CISU_GBCE_CONTROL_GAMMA_TYPE_CMC_COLOR_SPACE_SRGB,
    CISU_GBCE_CONTROL_GAMMA_TYPE_CMC_COLOR_SPACE_BT601,
    CISU_GBCE_CONTROL_GAMMA_TYPE_CMC_COLOR_SPACE_BT709,
    CISU_GBCE_CONTROL_GAMMA_TYPE_CMC_COLOR_SPACE_BT2020,
    CISU_GBCE_CONTROL_GAMMA_TYPE_CMC_COLOR_SPACE_BT2100_RGB,
    CISU_GBCE_CONTROL_GAMMA_TYPE_CMC_COLOR_SPACE_BT2100_LMS,
    CISU_GBCE_CONTROL_GAMMA_TYPE_CMC_COLOR_SPACE_DCI_P3,
    CISU_GBCE_CONTROL_GAMMA_TYPE_CMC_COLOR_SPACE_ADOBERGB,
};




// CISU_ISP_CONTROL_EFFECT_MODE
enum cisu_metadata_enum_cisu_isp_control_effect_mode {
    CISU_ISP_CONTROL_EFFECT_MODE_NONE,
    CISU_ISP_CONTROL_EFFECT_MODE_SKY_BLUE,
    CISU_ISP_CONTROL_EFFECT_MODE_GRASS_GREEN,
    CISU_ISP_CONTROL_EFFECT_MODE_SKIN_WHITE_LOW,
    CISU_ISP_CONTROL_EFFECT_MODE_SKIN_WHITEN,
    CISU_ISP_CONTROL_EFFECT_MODE_SKIN_WHITEN_HIGH,
    CISU_ISP_CONTROL_EFFECT_MODE_SEPIA,
    CISU_ISP_CONTROL_EFFECT_MODE_BLACK_AND_WHITE,
    CISU_ISP_CONTROL_EFFECT_MODE_NEGATIVE,
    CISU_ISP_CONTROL_EFFECT_MODE_VIVID,
    CISU_ISP_CONTROL_EFFECT_MODE_INVERT_GAMMA,
    CISU_ISP_CONTROL_EFFECT_MODE_GRAYSCALE,
    CISU_ISP_CONTROL_EFFECT_MODE_AQUA,
};

// CISU_ISP_CONTROL_NR_SETTING_LEVEL
enum cisu_metadata_enum_cisu_isp_control_nr_setting_level {
    CISU_ISP_CONTROL_NR_SETTING_LEVEL_OFF,
    CISU_ISP_CONTROL_NR_SETTING_LEVEL_LOW,
    CISU_ISP_CONTROL_NR_SETTING_LEVEL_HIGH,
};

// CISU_ISP_CONTROL_EE_SETTING_LEVEL
enum cisu_metadata_enum_cisu_isp_control_ee_setting_level {
    CISU_ISP_CONTROL_EE_SETTING_LEVEL_OFF,
    CISU_ISP_CONTROL_EE_SETTING_LEVEL_LOW,
    CISU_ISP_CONTROL_EE_SETTING_LEVEL_HIGH,
};


// CISU_DVS_CONTROL_DVS_OPERATION_MODE
enum cisu_metadata_enum_cisu_dvs_control_dvs_operation_mode {
    CISU_DVS_CONTROL_DVS_OPERATION_MODE_OFF                     = 0,
    CISU_DVS_CONTROL_DVS_OPERATION_MODE_MAX_AXIS                = 6,
    CISU_DVS_CONTROL_DVS_OPERATION_MODE_MOTION_SENSOR           = 10,
};


// CISU_SIMULATION_CONTROL_MODE
enum cisu_metadata_enum_cisu_simulation_control_mode {
    CISU_SIMULATION_CONTROL_MODE_OFF,
    CISU_SIMULATION_CONTROL_MODE_STILL,
    CISU_SIMULATION_CONTROL_MODE_VIDEO,
};

// CISU_SIMULATION_CONTROL_FILTER_INPUT_FILE_PATH_TYPE
enum cisu_metadata_enum_cisu_simulation_control_filter_input_file_path_type {
    CISU_SIMULATION_CONTROL_FILTER_INPUT_FILE_PATH_TYPE_RELATIVE,
    CISU_SIMULATION_CONTROL_FILTER_INPUT_FILE_PATH_TYPE_ABSOLUTE,
};


