/*
 * INTEL CONFIDENTIAL
 *
 * Copyright (C) 2015 - 2017 Intel Corporation.
 * All Rights Reserved.
 *
 * The source code contained or described herein and all documents
 * related to the source code ("Material") are owned by Intel Corporation
 * or licensors. Title to the Material remains with Intel Corporation
 * or its licensors. The Material contains trade secrets and proprietary
 * and confidential information of Intel or its licensors. The Material
 * is protected by worldwide copyright and trace secret laws and treaty
 * provisions. No part of the Material may beused, copied, reproduced,
 * modified, published, uploaded, posted, transmitted, distributed, or
 * disclosed in any way without Intel's prior express written permission.
 *
 * No License under any patent, copyright, trade secret or other intellectual
 * property right is granted to or conferred upon you by disclosure or
 * delivery of the Materials, either expressly, by implication, inducement,
 * estoppel or otherwise. Any license under such intellectual property rights
 * must be express and approved by Intel in writing.
 *
 */

#ifndef __IA_CSS_PSA_PARAMETER_DEFS_DEP_H
#define __IA_CSS_PSA_PARAMETER_DEFS_DEP_H

/* bxt B0 specific terminal specs. Common specs across platforms are defined in
 * ia_css_psa_parameter_defs.h
 */

#define IA_CSS_PSA_KERNEL_IS_PRIMARY_RYNR_SPLITTER                        (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_RYNR_COLLECTOR                       (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_RYNR_BNLM                            (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_RYNR_VCUD                            (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_LACE_LACE                            (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_ACM_CCM                              (0)
#define IA_CSS_PSA_KERNEL_IS_PRIMARY_ACM_ACM                              (0)


#define IA_CSS_PSA_NEEDS_SPATIAL_IN_RYNR_SPLITTER                         (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_RYNR_COLLECTOR                        (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_RYNR_BNLM                             (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_RYNR_VCUD                             (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_LACE_LACE                             (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_ACM_CCM                               (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_IN_ACM_ACM                               (0)


#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_RYNR_SPLITTER                        (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_RYNR_COLLECTOR                       (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_RYNR_BNLM                            (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_RYNR_VCUD                            (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_LACE_LACE                            (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_ACM_CCM                              (0)
#define IA_CSS_PSA_NEEDS_SPATIAL_OUT_ACM_ACM                              (0)

/* ==================== RYNR_SPLITTER specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_SPLITTER_SECTION_COUNT         (0)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_RYNR_SPLITTER_SECTION_COUNT     (0)

/* Spatial Parameter Terminal In does not exist for RYNR_SPLITTER */

/* Spatial Parameter Terminal Out does not exist for RYNR_SPLITTER */

#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_SPLITTER_SECTION_COUNT           (1)
#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_SPLITTER_MAX_SIZE_SECTION_0    (0x4)
#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_SPLITTER_DEST_OFFSET_SECTION_0 (0x0)
/* ==================== RYNR_SPLITTER specs - END ==================== */


/* ==================== RYNR_COLLECTOR specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_COLLECTOR_SECTION_COUNT         (1)
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_COLLECTOR_MAX_SIZE_SECTION_0    (0x8)
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_COLLECTOR_DEST_OFFSET_SECTION_0 (0x0)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_RYNR_COLLECTOR_SECTION_COUNT     (0)

/* Spatial Parameter Terminal In does not exist for RYNR_COLLECTOR */

/* Spatial Parameter Terminal Out does not exist for RYNR_COLLECTOR */

#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_COLLECTOR_SECTION_COUNT           (0)
/* ==================== RYNR_COLLECTOR specs - END ==================== */


/* ==================== RYNR_BNLM specs - START ==================== */
/* Note: multiple version are defined */
/* BNLM_VERSION_V1_1 */
#define	IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_BNLM_V1_1_SECTION_COUNT              (2)
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_BNLM_V1_1_MAX_SIZE_SECTION_0         (0x0020)
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_BNLM_V1_1_DEST_OFFSET_SECTION_0      (0x0004)
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_BNLM_V1_1_MAX_SIZE_SECTION_1         (0x0310)
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_BNLM_V1_1_DEST_OFFSET_SECTION_1      (0x0030)

/* Spatial Parameter Terminal In does not exist for RYNR_BNLM */

/* Spatial Parameter Terminal Out does not exist for RYNR_BNLM */

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_RYNR_BNLM_V1_1_SECTION_COUNT          (0)

#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_BNLM_V1_1_SECTION_COUNT                (2)
#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_BNLM_V1_1_MAX_SIZE_SECTION_0           (0x0004)
#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_BNLM_V1_1_DEST_OFFSET_SECTION_0        (0x0000)
#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_BNLM_V1_1_MAX_SIZE_SECTION_1           (0x000C)
#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_BNLM_V1_1_DEST_OFFSET_SECTION_1        (0x0024)

/* BNLM_VERSION_V1 (Default) */
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_BNLM_V1_SECTION_COUNT                (1)
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_BNLM_V1_MAX_SIZE_SECTION_0           (0x33C)
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_BNLM_V1_DEST_OFFSET_SECTION_0        (0x4)

/* Spatial Parameter Terminal In does not exist for RYNR_BNLM */

/* Spatial Parameter Terminal Out does not exist for RYNR_BNLM */

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_RYNR_BNLM_V1_SECTION_COUNT            (0)

#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_BNLM_V1_SECTION_COUNT                  (1)
#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_BNLM_V1_MAX_SIZE_SECTION_0             (0x4)
#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_BNLM_V1_DEST_OFFSET_SECTION_0          (0x0)

/* ==================== RYNR_BNLM specs - END ==================== */


/* ==================== RYNR_VCUD specs - START ==================== */
/* Note: multiple version are defined */
/* VCUD_VERSION_V1_1*/
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_1_SECTION_COUNT              (3)

#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_1_MAX_SIZE_SECTION_0         (0x0014)
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_1_DEST_OFFSET_SECTION_0      (0x0000)
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_1_MAX_SIZE_SECTION_1         (0x0020)
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_1_DEST_OFFSET_SECTION_1      (0x0018)
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_1_MAX_SIZE_SECTION_2         (0x00D4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_1_DEST_OFFSET_SECTION_2      (0x0044)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_RYNR_VCUD_V1_1_SECTION_COUNT          (0)

/* Spatial Parameter Terminal In does not exist for RYNR_VCUD */

/* Spatial Parameter Terminal Out does not exist for RYNR_VCUD */

#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_VCUD_V1_1_SECTION_COUNT                (3)

#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_VCUD_V1_1_MAX_SIZE_SECTION_0           (0x0004)
#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_VCUD_V1_1_DEST_OFFSET_SECTION_0        (0x0014)
#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_VCUD_V1_1_MAX_SIZE_SECTION_1           (0x000C)
#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_VCUD_V1_1_DEST_OFFSET_SECTION_1        (0x0038)
#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_VCUD_V1_1_MAX_SIZE_SECTION_2           (0x0020)
#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_VCUD_V1_1_DEST_OFFSET_SECTION_2        (0x0118)

/* VCUD_VERSION_V1 (Default)*/
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_SECTION_COUNT              (2)
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_MAX_SIZE_SECTION_0         (0x0014)
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_DEST_OFFSET_SECTION_0      (0x0000)
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_MAX_SIZE_SECTION_1         (0x0120)
#define IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_DEST_OFFSET_SECTION_1      (0x0018)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_RYNR_VCUD_V1_SECTION_COUNT          (0)

/* Spatial Parameter Terminal In does not exist for RYNR_VCUD */

/* Spatial Parameter Terminal Out does not exist for RYNR_VCUD */

#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_VCUD_V1_SECTION_COUNT                (1)
#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_VCUD_V1_MAX_SIZE_SECTION_0           (0x0004)
#define IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_VCUD_V1_DEST_OFFSET_SECTION_0        (0x0014)
/* ==================== RYNR_VCUD specs - END ==================== */


/* ==================== ACM_CCM specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_CCM_SECTION_COUNT                (2)
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_CCM_MAX_SIZE_SECTION_0           (0x4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_CCM_DEST_OFFSET_SECTION_0        (0x18)
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_CCM_MAX_SIZE_SECTION_1           (0x18)
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_CCM_DEST_OFFSET_SECTION_1        (0x0)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_ACM_CCM_SECTION_COUNT            (0)

/* Spatial Parameter Terminal In does not exist for ACM_CCM */

/* Spatial Parameter Terminal Out does not exist for ACM_CCM */

#define IA_CSS_PSA_PROGRAM_TERMINAL_ACM_CCM_SECTION_COUNT                  (0)
/* ==================== ACM_CCM specs - END ==================== */


/* ==================== ACM_ACM specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_ACM_SECTION_COUNT                (2)
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_ACM_MAX_SIZE_SECTION_0           (0x4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_ACM_DEST_OFFSET_SECTION_0        (0x0)
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_ACM_MAX_SIZE_SECTION_1           (0x358)
#define IA_CSS_PSA_PARAMETER_TERMINAL_ACM_ACM_DEST_OFFSET_SECTION_1        (0x4)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_ACM_ACM_SECTION_COUNT            (0)

/* Spatial Parameter Terminal In does not exist for ACM_ACM */

/* Spatial Parameter Terminal Out does not exist for ACM_ACM */

#define IA_CSS_PSA_PROGRAM_TERMINAL_ACM_ACM_SECTION_COUNT                  (0)
/* ==================== ACM_ACM specs - END ==================== */


/* ==================== DEMOSAIC_DEMOSAIC specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_DEMOSAIC_DEMOSAIC_SECTION_COUNT               (1)
#define IA_CSS_PSA_PARAMETER_TERMINAL_DEMOSAIC_DEMOSAIC_MAX_SIZE_SECTION_0          (0x30)
#define IA_CSS_PSA_PARAMETER_TERMINAL_DEMOSAIC_DEMOSAIC_DEST_OFFSET_SECTION_0       (0x4)

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_DEMOSAIC_DEMOSAIC_SECTION_COUNT           (0)

/* Spatial Parameter Terminal In does not exist for DEMOSAIC_DEMOSAIC */

/* Spatial Parameter Terminal Out does not exist for DEMOSAIC_DEMOSAIC */

#define IA_CSS_PSA_PROGRAM_TERMINAL_DEMOSAIC_DEMOSAIC_SECTION_COUNT                 (1)
#define IA_CSS_PSA_PROGRAM_TERMINAL_DEMOSAIC_DEMOSAIC_MAX_SIZE_SECTION_0            (0x4)
#define IA_CSS_PSA_PROGRAM_TERMINAL_DEMOSAIC_DEMOSAIC_DEST_OFFSET_SECTION_0         (0x0)
/* ==================== DEMOSAIC_DEMOSAIC specs - END ==================== */


/* ==================== YUV1_IEFD specs - START ==================== */
/* Note: multiple version are defined */
/* IEFD_INTERFACE_VERSION_X (Default) */
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_SECTION_COUNT              (3)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_MAX_SIZE_SECTION_0         (0x0004)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_DEST_OFFSET_SECTION_0      (0x0070)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_MAX_SIZE_SECTION_1         (0x0070)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_DEST_OFFSET_SECTION_1      (0x0000)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_MAX_SIZE_SECTION_2         (0x0058)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_DEST_OFFSET_SECTION_2      (0x0074)

/* Spatial Parameter Terminal In does not exist for YUV1_IEFD */

/* Spatial Parameter Terminal Out does not exist for YUV1_IEFD */

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_YUV1_IEFD_VX_SECTION_COUNT          (0)

#define IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_IEFD_VX_SECTION_COUNT                (0)

/* IEFD_INTERFACE_VERSION_X_1 */
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_SECTION_COUNT            (4)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_MAX_SIZE_SECTION_0       (0x0004)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_DEST_OFFSET_SECTION_0    (0x0070)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_MAX_SIZE_SECTION_1       (0x0070)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_DEST_OFFSET_SECTION_1    (0x0000)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_MAX_SIZE_SECTION_2       (0x0034)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_DEST_OFFSET_SECTION_2    (0x0074)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_MAX_SIZE_SECTION_3       (0x0018)
#define IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_DEST_OFFSET_SECTION_3    (0x00B4)

/* Spatial Parameter Terminal In does not exist for YUV1_IEFD */

/* Spatial Parameter Terminal Out does not exist for YUV1_IEFD */

#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_YUV1_IEFD_VX_1_SECTION_COUNT        (0)

#define IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_IEFD_VX_1_SECTION_COUNT              (1)
#define IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_IEFD_VX_1_MAX_SIZE_SECTION_0         (0x000C)
#define IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_IEFD_VX_1_DEST_OFFSET_SECTION_0      (0x00A8)
/* ==================== YUV1_IEFD specs - END ==================== */

/* ==================== LACE_LACE specs - START ==================== */
#define IA_CSS_PSA_PARAMETER_TERMINAL_LACE_LACE_SECTION_COUNT             (2)
#define IA_CSS_PSA_PARAMETER_TERMINAL_OUT_LACE_LACE_SECTION_COUNT         (0)
#define IA_CSS_PSA_PROGRAM_TERMINAL_LACE_LACE_SECTION_COUNT               (0)
/* ==================== LACE_LACE specs - END ==================== */

/* ==================== DVS specs - START ==================== */
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MAX_COMPUTE_UNITS_PER_SLICE        (84)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_COMPUTE_UNITS_PER_SLICE       (84)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MAX_COMPUTE_UNITS_PER_SLICE        (66)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_COMPUTE_UNITS_PER_SLICE       (66)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MAX_COMPUTE_UNITS_PER_SLICE        (45)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_COMPUTE_UNITS_PER_SLICE       (45)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_SECTION_COUNT                     (2)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_SECTION_COUNT                     (2)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_SECTION_COUNT                     (2)

#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH   (12)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L0_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT  (16)

#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH  (12)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L0_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT (16)

#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH   (11)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L1_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT  (16)

#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH  (11)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L1_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT (16)

#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH   (9)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_IN_DVS_L2_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT  (16)

#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_COMPUTE_UNITS_FRAGMENT_WIDTH  (9)
#define IA_CSS_PSA_SPATIAL_PARAMETER_TERMINAL_OUT_DVS_L2_MAX_COMPUTE_UNITS_FRAGMENT_HEIGHT (16)
/* ==================== DVS specs - END ==================== */


/* TODO: REMOVE BACKWARD COMPATIBILITY */
#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_SPLITTER_SECTION_COUNT          IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_SPLITTER_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_RYNR_SPLITTER_SECTION_COUNT      IA_CSS_PSA_PARAMETER_TERMINAL_OUT_RYNR_SPLITTER_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_SPLITTER_SECTION_COUNT            IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_SPLITTER_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_SPLITTER_MAX_SIZE_SECTION_0       IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_SPLITTER_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_SPLITTER_DEST_OFFSET_SECTION_0    IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_SPLITTER_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_COLLECTOR_SECTION_COUNT         IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_COLLECTOR_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_COLLECTOR_MAX_SIZE_SECTION_0    IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_COLLECTOR_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_COLLECTOR_DEST_OFFSET_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_COLLECTOR_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_RYNR_COLLECTOR_SECTION_COUNT     IA_CSS_PSA_PARAMETER_TERMINAL_OUT_RYNR_COLLECTOR_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_COLLECTOR_SECTION_COUNT           IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_COLLECTOR_SECTION_COUNT

#if( defined(BNLM_VERSION_V1_1) )
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_BNLM_SECTION_COUNT         IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_BNLM_V1_1_SECTION_COUNT
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_BNLM_MAX_SIZE_SECTION_0    IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_BNLM_V1_1_MAX_SIZE_SECTION_0
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_BNLM_DEST_OFFSET_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_BNLM_V1_1_DEST_OFFSET_SECTION_0
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_BNLM_MAX_SIZE_SECTION_1    IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_BNLM_V1_1_MAX_SIZE_SECTION_1
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_BNLM_DEST_OFFSET_SECTION_1 IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_BNLM_V1_1_DEST_OFFSET_SECTION_1
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_RYNR_BNLM_SECTION_COUNT     IA_CSS_PSA_PARAMETER_TERMINAL_OUT_RYNR_BNLM_V1_1_SECTION_COUNT
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_BNLM_SECTION_COUNT           IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_BNLM_V1_1_SECTION_COUNT
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_BNLM_MAX_SIZE_SECTION_0      IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_BNLM_V1_1_MAX_SIZE_SECTION_0
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_BNLM_DEST_OFFSET_SECTION_0   IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_BNLM_V1_1_DEST_OFFSET_SECTION_0
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_BNLM_MAX_SIZE_SECTION_1      IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_BNLM_V1_1_MAX_SIZE_SECTION_1
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_BNLM_DEST_OFFSET_SECTION_1   IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_BNLM_V1_1_DEST_OFFSET_SECTION_1
#else
	/* Default BNLM_VERSION_V1 */
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_BNLM_SECTION_COUNT         IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_BNLM_V1_SECTION_COUNT
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_BNLM_MAX_SIZE_SECTION_0    IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_BNLM_V1_MAX_SIZE_SECTION_0
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_BNLM_DEST_OFFSET_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_BNLM_V1_DEST_OFFSET_SECTION_0
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_RYNR_BNLM_SECTION_COUNT     IA_CSS_PSA_PARAMETER_TERMINAL_OUT_RYNR_BNLM_V1_SECTION_COUNT
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_BNLM_SECTION_COUNT           IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_BNLM_V1_SECTION_COUNT
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_BNLM_MAX_SIZE_SECTION_0      IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_BNLM_V1_MAX_SIZE_SECTION_0
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_BNLM_DEST_OFFSET_SECTION_0   IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_BNLM_V1_DEST_OFFSET_SECTION_0
#endif /* BNLM_VERSION */

#if( defined(VCUD_VERSION_V1_1) )
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_VCUD_SECTION_COUNT         IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_1_SECTION_COUNT
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_VCUD_MAX_SIZE_SECTION_0    IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_1_MAX_SIZE_SECTION_0
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_VCUD_DEST_OFFSET_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_1_DEST_OFFSET_SECTION_0
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_VCUD_MAX_SIZE_SECTION_1    IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_1_MAX_SIZE_SECTION_1
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_VCUD_DEST_OFFSET_SECTION_1 IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_1_DEST_OFFSET_SECTION_1
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_VCUD_MAX_SIZE_SECTION_2    IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_1_MAX_SIZE_SECTION_2
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_VCUD_DEST_OFFSET_SECTION_2 IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_1_DEST_OFFSET_SECTION_2
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_RYNR_VCUD_SECTION_COUNT     IA_CSS_PSA_PARAMETER_TERMINAL_OUT_RYNR_VCUD_V1_1_SECTION_COUNT
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_VCUD_SECTION_COUNT           IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_VCUD_V1_1_SECTION_COUNT
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_VCUD_MAX_SIZE_SECTION_0      IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_VCUD_V1_1_MAX_SIZE_SECTION_0
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_VCUD_DEST_OFFSET_SECTION_0   IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_VCUD_V1_1_DEST_OFFSET_SECTION_0
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_VCUD_MAX_SIZE_SECTION_1      IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_VCUD_V1_1_MAX_SIZE_SECTION_1
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_VCUD_DEST_OFFSET_SECTION_1   IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_VCUD_V1_1_DEST_OFFSET_SECTION_1
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_VCUD_MAX_SIZE_SECTION_2      IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_VCUD_V1_1_MAX_SIZE_SECTION_2
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_VCUD_DEST_OFFSET_SECTION_2   IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_VCUD_V1_1_DEST_OFFSET_SECTION_2

#else
	/* Default VCUD_VERSION_V1 */
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_VCUD_SECTION_COUNT         IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_SECTION_COUNT
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_VCUD_MAX_SIZE_SECTION_0    IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_MAX_SIZE_SECTION_0
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_VCUD_DEST_OFFSET_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_DEST_OFFSET_SECTION_0
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_VCUD_MAX_SIZE_SECTION_1    IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_MAX_SIZE_SECTION_1
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_RYNR_VCUD_DEST_OFFSET_SECTION_1 IA_CSS_PSA_PARAMETER_TERMINAL_RYNR_VCUD_V1_DEST_OFFSET_SECTION_1
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_RYNR_VCUD_SECTION_COUNT     IA_CSS_PSA_PARAMETER_TERMINAL_OUT_RYNR_VCUD_V1_SECTION_COUNT
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_VCUD_SECTION_COUNT           IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_VCUD_V1_SECTION_COUNT
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_VCUD_MAX_SIZE_SECTION_0      IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_VCUD_V1_MAX_SIZE_SECTION_0
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_RYNR_VCUD_DEST_OFFSET_SECTION_0   IA_CSS_PSA_PROGRAM_TERMINAL_RYNR_VCUD_V1_DEST_OFFSET_SECTION_0
#endif /* VCUD_VERSION */

#define IA_CSS_PSYS_PARAMETER_TERMINAL_ACM_CCM_SECTION_COUNT                   IA_CSS_PSA_PARAMETER_TERMINAL_ACM_CCM_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_ACM_CCM_MAX_SIZE_SECTION_0              IA_CSS_PSA_PARAMETER_TERMINAL_ACM_CCM_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_ACM_CCM_DEST_OFFSET_SECTION_0           IA_CSS_PSA_PARAMETER_TERMINAL_ACM_CCM_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_ACM_CCM_MAX_SIZE_SECTION_1              IA_CSS_PSA_PARAMETER_TERMINAL_ACM_CCM_MAX_SIZE_SECTION_1
#define IA_CSS_PSYS_PARAMETER_TERMINAL_ACM_CCM_DEST_OFFSET_SECTION_1           IA_CSS_PSA_PARAMETER_TERMINAL_ACM_CCM_DEST_OFFSET_SECTION_1
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_ACM_CCM_SECTION_COUNT               IA_CSS_PSA_PARAMETER_TERMINAL_OUT_ACM_CCM_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_ACM_CCM_SECTION_COUNT                     IA_CSS_PSA_PROGRAM_TERMINAL_ACM_CCM_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_ACM_ACM_SECTION_COUNT                   IA_CSS_PSA_PARAMETER_TERMINAL_ACM_ACM_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_ACM_ACM_MAX_SIZE_SECTION_0              IA_CSS_PSA_PARAMETER_TERMINAL_ACM_ACM_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_ACM_ACM_DEST_OFFSET_SECTION_0           IA_CSS_PSA_PARAMETER_TERMINAL_ACM_ACM_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_ACM_ACM_MAX_SIZE_SECTION_1              IA_CSS_PSA_PARAMETER_TERMINAL_ACM_ACM_MAX_SIZE_SECTION_1
#define IA_CSS_PSYS_PARAMETER_TERMINAL_ACM_ACM_DEST_OFFSET_SECTION_1           IA_CSS_PSA_PARAMETER_TERMINAL_ACM_ACM_DEST_OFFSET_SECTION_1
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_ACM_ACM_SECTION_COUNT               IA_CSS_PSA_PARAMETER_TERMINAL_OUT_ACM_ACM_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_ACM_ACM_SECTION_COUNT                     IA_CSS_PSA_PROGRAM_TERMINAL_ACM_ACM_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_DEMOSAIC_DEMOSAIC_SECTION_COUNT         IA_CSS_PSA_PARAMETER_TERMINAL_DEMOSAIC_DEMOSAIC_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_DEMOSAIC_DEMOSAIC_MAX_SIZE_SECTION_0    IA_CSS_PSA_PARAMETER_TERMINAL_DEMOSAIC_DEMOSAIC_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_DEMOSAIC_DEMOSAIC_DEST_OFFSET_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_DEMOSAIC_DEMOSAIC_DEST_OFFSET_SECTION_0
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_DEMOSAIC_DEMOSAIC_SECTION_COUNT     IA_CSS_PSA_PARAMETER_TERMINAL_OUT_DEMOSAIC_DEMOSAIC_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_DEMOSAIC_DEMOSAIC_SECTION_COUNT           IA_CSS_PSA_PROGRAM_TERMINAL_DEMOSAIC_DEMOSAIC_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_DEMOSAIC_DEMOSAIC_MAX_SIZE_SECTION_0      IA_CSS_PSA_PROGRAM_TERMINAL_DEMOSAIC_DEMOSAIC_MAX_SIZE_SECTION_0
#define IA_CSS_PSYS_PROGRAM_TERMINAL_DEMOSAIC_DEMOSAIC_DEST_OFFSET_SECTION_0   IA_CSS_PSA_PROGRAM_TERMINAL_DEMOSAIC_DEMOSAIC_DEST_OFFSET_SECTION_0

#if defined(IEFD_INTERFACE_VERSION_X_1)
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_SECTION_COUNT         IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_SECTION_COUNT
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_MAX_SIZE_SECTION_0    IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_MAX_SIZE_SECTION_0
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_DEST_OFFSET_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_DEST_OFFSET_SECTION_0
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_MAX_SIZE_SECTION_1    IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_MAX_SIZE_SECTION_1
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_DEST_OFFSET_SECTION_1 IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_DEST_OFFSET_SECTION_1
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_MAX_SIZE_SECTION_2    IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_MAX_SIZE_SECTION_2
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_DEST_OFFSET_SECTION_2 IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_DEST_OFFSET_SECTION_2
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_MAX_SIZE_SECTION_3    IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_MAX_SIZE_SECTION_3
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_DEST_OFFSET_SECTION_3 IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_1_DEST_OFFSET_SECTION_3
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_YUV1_IEFD_SECTION_COUNT     IA_CSS_PSA_PARAMETER_TERMINAL_OUT_YUV1_IEFD_VX_1_SECTION_COUNT
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_YUV1_IEFD_SECTION_COUNT           IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_IEFD_VX_1_SECTION_COUNT
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_YUV1_IEFD_MAX_SIZE_SECTION_0      IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_IEFD_VX_1_MAX_SIZE_SECTION_0
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_YUV1_IEFD_DEST_OFFSET_SECTION_0   IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_IEFD_VX_1_DEST_OFFSET_SECTION_0
#else
	/* Default IEFD_INTERFACE_VERSION_X) */
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_SECTION_COUNT         IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_SECTION_COUNT
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_MAX_SIZE_SECTION_0    IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_MAX_SIZE_SECTION_0
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_DEST_OFFSET_SECTION_0 IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_DEST_OFFSET_SECTION_0
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_MAX_SIZE_SECTION_1    IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_MAX_SIZE_SECTION_1
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_DEST_OFFSET_SECTION_1 IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_DEST_OFFSET_SECTION_1
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_MAX_SIZE_SECTION_2    IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_MAX_SIZE_SECTION_2
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_YUV1_IEFD_DEST_OFFSET_SECTION_2 IA_CSS_PSA_PARAMETER_TERMINAL_YUV1_IEFD_VX_DEST_OFFSET_SECTION_2
	#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_YUV1_IEFD_SECTION_COUNT     IA_CSS_PSA_PARAMETER_TERMINAL_OUT_YUV1_IEFD_VX_SECTION_COUNT
	#define IA_CSS_PSYS_PROGRAM_TERMINAL_YUV1_IEFD_SECTION_COUNT           IA_CSS_PSA_PROGRAM_TERMINAL_YUV1_IEFD_VX_SECTION_COUNT
#endif /* IEFD_INTERFACE_VERSION_X_1 */
#define IA_CSS_PSYS_PARAMETER_TERMINAL_LACE_LACE_SECTION_COUNT                 IA_CSS_PSA_PARAMETER_TERMINAL_LACE_LACE_SECTION_COUNT
#define IA_CSS_PSYS_PARAMETER_TERMINAL_OUT_LACE_LACE_SECTION_COUNT             IA_CSS_PSA_PARAMETER_TERMINAL_OUT_LACE_LACE_SECTION_COUNT
#define IA_CSS_PSYS_PROGRAM_TERMINAL_LACE_LACE_SECTION_COUNT                   IA_CSS_PSA_PROGRAM_TERMINAL_LACE_LACE_SECTION_COUNT

#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_RYNR_SPLITTER                            IA_CSS_PSA_KERNEL_IS_PRIMARY_RYNR_SPLITTER
#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_RYNR_COLLECTOR                           IA_CSS_PSA_KERNEL_IS_PRIMARY_RYNR_COLLECTOR
#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_RYNR_BNLM                                IA_CSS_PSA_KERNEL_IS_PRIMARY_RYNR_BNLM
#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_RYNR_VCUD                                IA_CSS_PSA_KERNEL_IS_PRIMARY_RYNR_VCUD
#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_LACE_LACE                                IA_CSS_PSA_KERNEL_IS_PRIMARY_LACE_LACE
#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_ACM_CCM                                  IA_CSS_PSA_KERNEL_IS_PRIMARY_ACM_CCM
#define IA_CSS_PSYS_KERNEL_IS_PRIMARY_ACM_ACM                                  IA_CSS_PSA_KERNEL_IS_PRIMARY_ACM_ACM
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_RYNR_SPLITTER                             IA_CSS_PSA_NEEDS_SPATIAL_IN_RYNR_SPLITTER
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_RYNR_COLLECTOR                            IA_CSS_PSA_NEEDS_SPATIAL_IN_RYNR_COLLECTOR
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_RYNR_BNLM                                 IA_CSS_PSA_NEEDS_SPATIAL_IN_RYNR_BNLM
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_RYNR_VCUD                                 IA_CSS_PSA_NEEDS_SPATIAL_IN_RYNR_VCUD
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_LACE_LACE                                 IA_CSS_PSA_NEEDS_SPATIAL_IN_LACE_LACE
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_ACM_CCM                                   IA_CSS_PSA_NEEDS_SPATIAL_IN_ACM_CCM
#define IA_CSS_PSYS_NEEDS_SPATIAL_IN_ACM_ACM                                   IA_CSS_PSA_NEEDS_SPATIAL_IN_ACM_ACM
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_RYNR_SPLITTER                            IA_CSS_PSA_NEEDS_SPATIAL_OUT_RYNR_SPLITTER
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_RYNR_COLLECTOR                           IA_CSS_PSA_NEEDS_SPATIAL_OUT_RYNR_COLLECTOR
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_RYNR_BNLM                                IA_CSS_PSA_NEEDS_SPATIAL_OUT_RYNR_BNLM
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_RYNR_VCUD                                IA_CSS_PSA_NEEDS_SPATIAL_OUT_RYNR_VCUD
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_LACE_LACE                                IA_CSS_PSA_NEEDS_SPATIAL_OUT_LACE_LACE
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_ACM_CCM                                  IA_CSS_PSA_NEEDS_SPATIAL_OUT_ACM_CCM
#define IA_CSS_PSYS_NEEDS_SPATIAL_OUT_ACM_ACM                                  IA_CSS_PSA_NEEDS_SPATIAL_OUT_ACM_ACM

/* END OF TODO */

#endif /* __IA_CSS_PSA_PARAMETER_DEFS_DEP_H */
